=== Outsmart-OOH/ooh_open_direct/schema/v1/resources/line/line_object.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://raw.githubusercontent.com/Outsmart-OOH/ooh_open_direct/master/schema/v1/resources/line/line_object.json",
  "type": "object",
  "title": "Line object",
  "description": "Template container for Line, still to be populated",
  "default": {},
  "additionalProperties": false,
  "properties": {
      "$schema": {
          "type": "string",
          "format": "uri",
          "description": "$schema only included to aid validation of JSON, should not be used in real calls."
      },
      "BookingStatus": {
          "$id": "#/properties/BookingStatus",
          "type": "string",
          "title": "Booking Status",
          "description": "A value that determines whether the line is booked and is capable of delivering ads. For a states , see Booking Status Values."
      },
      "Comment": {
          "$id": "#/properties/Comment",
          "type": "string",
          "title": "Comment",
          "description": "User notes related to this line."
      },
      "Cost": {
          "$id": "#/properties/Cost",
          "type": "number",
          "title": "Cost",
          "description": "The projected cost of the line is based on the specified targeting. "
      },
      "EndDate": {
          "$id": "#/properties/EndDate",
          "type": "string",
          "format": "date-time",
          "title": "End Date",
          "description": "The date and time that the line will stop."
      },
      "Id": {
          "$ref": "https://raw.githubusercontent.com/Outsmart-OOH/ooh_open_direct/master/schema/v1/resources/line/line_id_string.json"
      },
      "Name": {
          "$id": "#/properties/Name",
          "type": "string",
          "title": "Line Name",
          "description": "The line's display name. The name must be unique."
      },
      "OrderId": {
          "$id": "#/properties/OrderId",
          "type": "string",
          "title": "Order ID",
          "description": "The ID of the order that this line belongs to."
      },
      "ProductId": {
          "$id": "#/properties/ProductId",
          "type": "string",
          "title": "Product ID",
          "description": "The ID of the product where the creatives run."
      },
      "ProviderData": {
          "$id": "#/properties/ProviderData",
          "type": "string",
          "title": "Provider Data",
          "description": "An opaque CLOB of provider-defined data. "
      },
      "OOHProviderData": {
          "$id": "#/properties/OOHProviderData",
          "description": "The OOHProviderData object is used for Buyers to detail structured information",
          "type": "object",
          "$ref": "https://raw.githubusercontent.com/Outsmart-OOH/ooh_open_direct/master/schema/v1/common/oohProviderData_object.json"
      },
      "ReservedExpiryDate": {
          "$id": "#/properties/ReservedExpiryDate",
          "type": "string",
          "format": "date-time",
          "title": "Reserved Expiry Date",
          "description": "The date and time that the reserved inventory will expire. If the line is reserved, the expiry date must be set."
      },
      "StartDate": {
          "$id": "#/properties/StartDate",
          "type": "string",
          "format": "date-time",
          "title": "Start Date",
          "description": "The date and time that the line will start."
      },
      "StateChangeReason": {
          "$id": "#/properties/StateChangeReason",
          "type": "string",
          "title": "State Change Reason",
          "description": "The reason why the state was changed by the publisher. The reason must be specified if: The publisher declined the booking or reservation, The publisher or user canceled the flight."
      },
      "Stats": {
          "$id": "#/properties/Stats",
          "type": "object",
          "title": "Stats",
          "description": "Reports on the schedule generated to fulfill the targeting requirements detailed in the Order Line (pre-flight stage), and the performance of the schedule when the campaign is in flight and/or completed."
      },
      "Targeting": {
          "$id": "#/properties/Targeting",
          "$ref": "https://raw.githubusercontent.com/Outsmart-OOH/ooh_open_direct/master/schema/v1/common/targetTypes_array.json"
      },
      "ProductUnAvails": {
          "$id": "#/properties/ProductUnAvails",
          "type": "array",
          "title": "Array of ProductUnAvails",
          "description": "This Object is used to show the EXCEPTION where the draft/reserve/booking request failed because of a change in product availability between booking states",
          "items": {
              "$ref": "https://raw.githubusercontent.com/Outsmart-OOH/ooh_open_direct/master/schema/v1/common/productAvails_object.json",
              "required": [
                  "Currency",
                  "ProductId",
                  "Targeting",
                  "Price"
              ]
          }
      },
      "ProductAvails": {
          "$id": "#/properties/ProductAvails",
          "type": "array",
          "title": "Array of ProductAvails",
          "description": "This Object is used to return the latest Product Avails in the event of the line draft/reserve/booking request failing because of a change in product availability between booking states",
          "items": {
              "$ref": "https://raw.githubusercontent.com/Outsmart-OOH/ooh_open_direct/master/schema/v1/common/productAvails_object.json",
              "required": [
                  "Currency",
                  "ProductId",
                  "Targeting",
                  "Price"
              ]
          }
      }
  }
}

=== Outsmart-OOH/ooh_open_direct/examples/OOHpenDirect_1-5-1_v-1/POST_lines_idX_request.json
{
    "$schema": "https://raw.githubusercontent.com/Outsmart-OOH/ooh_open_direct/master/schema/v1/uris/lines/lines_request.json",
    "Comment": "Free form comment",
    "EndDate": "2020-11-08T00:00:00.000Z",
    "Name": "Big Line 1",
    "ProductId": "456366",
    "OOHProviderData": {
        "PoNumber": "88888"
    },
    "StartDate": "2020-11-02T00:00:00.000Z",
    "Targeting": [
        {
            "Name": "Inventory",
            "Type": "Frames",
            "DataSource": "Space",
            "Target": "frame_id",
            "TargetValues": [
                "1234931339",
                "1235190735",
                "1234931338",
                "1235191547"
            ]
        },
        {
            "Name": "Delivery",
            "Type": "Frames",
            "DataSource": "Time",
            "Target": "Days",
            "TargetValues": [
                "6"
            ]
        },
        {
            "Name": "Delivery",
            "Type": "Frames",
            "DataSource": "Time",
            "Target": "Hours",
            "TargetValues": [
                "7",
                "8",
                "9"
            ]
        },
        {
            "Name": "Delivery",
            "Type": "Frames",
            "DataSource": "ShareOfDisplay",
            "Target": "ShareOfTime",
            "TargetValues": [
                "20"
            ]
        },
        {
            "Name": "Delivery",
            "Type": "Frames",
            "DataSource": "ShareOfDisplay",
            "Target": "Spot",
            "TargetValues": [
                "5"
            ]
        }
    ]
}
