=== Outsmart-OOH/ooh_open_direct/schema/v1_poc_backup10May21/resources/order/order_object.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "https://raw.githubusercontent.com/Outsmart-OOH/ooh_open_direct/master/schema/v1/resources/order/order_object.json",
    "type": "object",
    "title": "Order object",
    "description": "Template container for Order, still to be populated",
    "default": {},
    "additionalProperties": false,
    "properties": {
        "$schema": {
            "type": "string",
            "format": "uri",
            "description": "$schema only included to aid validation of JSON, should not be used in real calls."
        },
        "AccountId": {
            "$id": "#/properties/AccountId",
            "type": "string",
            "title": "Account ID",
            "description": "The ID of the account that identifies the advertiser and buyer that own the order.",
            "maxLength": 36
        },
        "AdvertiserBrandId":{
            "$id": "#/properties/AdvertiserBrandId",
            "type": "string",
            "title": "Advertiser Brand ID",
            "description": "The id of the AdvertiserBrand being advertised ",
            "maxLength": 25
        },
        "Budget":{
            "$id": "#/properties/Budget",
            "type": "number",
            "title": "Budget",
            "description": "The order’s estimated budget. The budget is directional; it is not used to limit the amount of money that the order spends. To determine the projected spend based on quantity, aggregate the Cost property for each line of the order."
        },
        "Contacts":{
            "$id": "#/properties/Contacts",
            "type": "array",
            "title": "Contacts",
            "description": "A list of one or more contacts with the organisation",
            "$ref":"https://raw.githubusercontent.com/Outsmart-OOH/ooh_open_direct/master/schema/v1/common/contact_object.json"
        },
        "Currency":{
            "$id": "#/properties/Currency",
            "type": "string",
            "title": "Currency",
            "description": "The currency that all monetary properties of the order and lines are specified in. The currency is also used for billing and reporting. Values are provided using the CURRENCY reference data as specified in section 4.5.",
            "maxLength": 3
        },
        "EndDate":{
            "$id": "#/properties/EndDate",
            "type": "string",
            "format": "date-time",
            "title": "Order",
            "description": "The date and time that the order will end. The end date is directional and may be updated by the publisher to match the latest end date found in the order’s lines.The date and time must be specified in UTC and conform to ISO 8601. If the time is missing, 11:59 PM is assumed.The end date must be later than the start date. End dates that have past cannot be updated."
        },
        "OrderExpiryDate":{
            "$id": "#/properties/OrderExpiryDate",
            "type": "string",
            "format": "date-time",
            "title": "Order Expiry Date",
            "description": "The date and time using the ISO 8601 format for when the order expires. Publisher will only hold inventory up until the date and time indicated."
        },
        "Id": {
            "$ref": "https://raw.githubusercontent.com/Outsmart-OOH/ooh_open_direct/master/schema/v1/resources/order/order_id_string.json"
        },
        "Industry": {
            "$id": "#/properties/Industry",
            "type":"object",
            "properties": {},
            "title": "Industry",
            "description": "The industry associated with the order. This industry may differ from the industry specified on the advertiser’s Organization object."
        },
        "Name": {
            "$id": "#/properties/Name",
            "type": "string",
            "title": "Order Name",
            "description": "The order's display name. The name must be unique.",
            "maxLength": 100
        },
        "OrderStatus": {
            "$id": "#/properties/OrderSratus",
            "type": "string",
            "title": "Order Status",
            "description": "Specifies the Status of the Order **PENDING** – The Order has not yet been approved/rejected **APPROVED** – The Order has been approved **REJECTED** – The Order has been rejected",
            "enum": ["PENDING", "APPROVED", "REJECTED"]
        }, 
        "PreferredBillingMethod":{
            "$id": "#/properties/PreferredBillingMethod",
            "type": "string",
            "title": "Preferred Billing Method",
            "description": "Electronic (Default) or Postal",
            "enum": ["Electronic", "Postal"]
        },
        "ProviderData": {
            "$id": "#/properties/OOHProviderData",
            "description": "An opaque CLOB of provider-defined data. ",
            "type": "string",
            "maxLength": 1000
        },
        "OOHProviderData": {
            "$id": "#/properties/OOHProviderData",
            "description": "Detail structured information that may be used to identify their order in a Seller's system using their own IDs or reference",
            "type": "object",
            "$ref": "https://raw.githubusercontent.com/Outsmart-OOH/ooh_open_direct/master/schema/v1/common/oohProviderData_object.json"
        },
        "StartDate": {
            "$id": "#/properties/StartDate",
            "description": "The date and time that the order will start. The start date is directional and may be updated by the publisher to match the earliest start date found in the order’s list of lines.The date and time must be specified in UTC and conform to ISO 8601. If the time is missing, 12:00 AM is assumed. When creating the order, the date and time must be greater than or equal to now. Start dates that have past may not be updated.",
            "type": "string",
            "format": "date-time"
        }
    }
}

=== Outsmart-OOH/ooh_open_direct/examples/OOHpenDirect_1-5-1_v-1/GET_orders_id_response.json
{
  "$schema": "https://raw.githubusercontent.com/Outsmart-OOH/ooh_open_direct/master/schema/v1/uris/orders/orders_response.json",
  
  "AccountId": "23873345",
  "AdvertiserBrandId": "73",
  "Currency": "GBP",
  "EndDate": "2014-12-24T18:00:00.000Z",
  "Id": "1235872",
  "Name": "My Order",
  "PreferredBillingMethod": "Electronic",
  "OOHProviderData": 
    {
      "CampaignId": "B007",
      "CampaignName": "BARTYTIME",
      "PoNumber": "",
      "SalesOrderReference": "SPEC123",
      "BarterOrganizationID": "BAR987",
      "Other": ""
    }
  ,
  "StartDate": "2014-11-24T06:00:00.000Z"
 
}

=== Outsmart-OOH/ooh_open_direct/examples/OOHpenDirect_1-5-1_v-1/POST_orders_request.json
{
    "$schema": "https://raw.githubusercontent.com/Outsmart-OOH/ooh_open_direct/master/schema/v1/uris/orders/orders_request.json",
    "Id":"orderid",
    "AccountId": "23873345",
    "AdvertiserBrandId": "73",
    "Currency": "GBP",
    "EndDate": "2014-12-24T18:00:00.000Z",
    "Name": "My Order",
    "OOHProviderData": 
        {
            "CampaignId": "B007",
            "CampaignName": "BARTYTIME",
            "PoNumber": "",
            "SalesOrderReference": "SPEC123",
            "BarterOrganizationID": "BAR987",
            "Other":""
        },
    "StartDate": "2014-11-24T06:00:00.000Z"
}
