=== Outsmart-OOH/ooh_open_direct/examples/Worksheets/OOHbjectUsageSchema/common/productAvailsSearch_object.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "https://raw.githubusercontent.com/Outsmart-OOH/ooh_open_direct/master/schema/v1/common/productAvailsSearch_object.json",
    "type": "object",
    "title": "ProductAvailsSearch object",
    "description": "",
    "default": {},
    "additionalProperties": false,
    "properties": {
        "$schema": {
            "type": "string",
            "format": "uri",
            "description": "$schema only included to aid validation of JSON, should not be used in real calls."
        },
        "AccountId": {
            "$id": "#/properties/AccountId",
            "type": "string",
            "title": "Account ID",
            "description": "The ID of the account that identifies the buyer, advertiser and any other stakeholders."
        },
        "AdvertiserBrandId": {
            "$id": "#/properties/AdvertiserBrandId",
            "type": "string"
        },
        "Currency": {
            "$id": "#/properties/Currency",
            "type": "string"
        },
        "ProductIds": {
            "$id": "#/properties/ProductIds",
            "type": "array",
            "title": "Product IDs",
            "description": "A list of IDs that identify the products on which to get availability and pricing information",
            "items": {
                "$id": "#/properties/ProductIds/items",
                "type": "string"
            }
        },
        "EndDate": {
            "$id": "#/properties/EndDate",
            "type": "string",
            "format": "date-time",
            "title": "End Date",
            "description": "The desired end date for inventory delivery"
        },
        "StartDate": {
            "$id": "#/properties/StartDate",
            "type": "string",
            "format": "date-time",
            "title": "Start Date",
            "description": "The desired start date for inventory delivery"
        },
        "AvailabilityFields": {
            "$id": "#/properties/AvailabilityFields",
            "type": "array",
            "additionalItems": true,
            "items": {
                "$id": "#/properties/AvailabilityFields/items",
                "type": "object",
                "additionalProperties": true,
                "required": [
                    "Name",
                    "Type",
                    "DataSource",
                    "Target"
                ],
                "properties": {
                    "Name": {
                        "$id": "#/properties/AvailabilityFields/items/properties/Name",
                        "type": "string"
                    },
                    "Type": {
                        "$id": "#/properties/AvailabilityFields/items/properties/Type",
                        "type": "string"
                    },
                    "DataSource": {
                        "$id": "#/properties/AvailabilityFields/items/properties/DataSource",
                        "type": "string"
                    },
                    "Target": {
                        "$id": "#/properties/AvailabilityFields/items/properties/Target",
                        "type": "string"
                    }
                }
            }
        },
        "Grouping": {
            "$id": "#/properties/Grouping",
            "type": "array",
            "title": "Grouping",
            "description": "Defines the OOHbject metric that the availability output is grouped as.",
            "items": {
                "$id": "#/properties/Grouping/items",
                "type": "object",
                "additionalProperties": true,
                "required": [
                    "Name",
                    "Type",
                    "DataSource",
                    "Target"
                ],
                "properties": {
                    "Name": {
                        "$id": "#/properties/Grouping/items/properties/Name",
                        "type": "string"
                    },
                    "Type": {
                        "$id": "#/properties/Grouping/items/properties/Type",
                        "type": "string"
                    },
                    "DataSource": {
                        "$id": "#/properties/Grouping/items/properties/DataSource",
                        "type": "string"
                    },
                    "Target": {
                        "$id": "#/properties/Grouping/items/properties/Target",
                        "type": "string"
                    }
                }
            }
        },
        "Targeting": {
            "$id": "#/properties/Targeting",
            "$ref": "https://raw.githubusercontent.com/Outsmart-OOH/ooh_open_direct/master/schema/v1/common/targetTypes_array.json"
        }
    }
}

=== Outsmart-OOH/ooh_open_direct/examples/Worksheets/OOHbjectUsageSchema/example_GET_avails_request.json
{
    "$schema": "https://raw.githubusercontent.com/Outsmart-OOH/ooh_open_direct/master/examples/Worksheets/OOHbjectUsageSchema/uris/products/products_avails_request.json",
    "AccountId": "23873345",
    "EndDate": "2014-12-10T18:00:00.000Z",
    "ProductIds": [ "456367" ],
    "StartDate": "2014-12-05T06:00:00.000Z",

    "AvailabilityFields": [

        {
            "Name": "Inventory",
            "Type": "Frames",
            "DataSource": "SPACE",
            "Target": "frame_id"
        },
        {
            "Name": "Delivery",
            "Type": "Frames",
            "DataSource": "ShareOfDisplay",
            "Target": "ShareOfTime"
        },
        {
            "Name": "Inventory",
            "Type": "Audience",
            "DataSource": "Metrics",
            "Target": "Impacts"
        },
        {
            "Name": "Investment",
            "Type": "Total",
            "DataSource": "GBP",
            "Target": "Fixed"
        }
    ],


    "Grouping": [
        {
            "Name": "Inventory",
            "Type": "Frames",
            "DataSource": "SPACE",
            "Target": "frame_id"
        }
    ],

    "Targeting": [
        {
            "Name": "Inventory",
            "Type": "Frames",
            "DataSource": "Space",
            "Target": "<FrameId>",
            "TargetValues": [
                "1234931339",
                "1235190735",
                "1234931338",
                "1235191547"
            ]
        },
        {
            "Name": "Delivery",
            "Type": "Frames",
            "DataSource": "Time",
            "Target": "Days",
            "TargetValues": [ "5", "6" ]

        },
        {
            "Name": "Delivery",
            "Type": "Frames",
            "DataSource": "ShareOfDisplay",
            "Target": "ShareOfTime",
            "TargetValues": ["20"]

        },
        {
            "Name": "Delivery",
            "Type": "Frames",
            "DataSource": "ShareOfDisplay",
            "Target": "Spot",
            "TargetValues": ["5"]
        },
        {
            "Name":"Inventory",
            "Type": "Frames",
            "DataSource": "Space",
            "Target": "FramesCount",
            "Minimum": 2,
            "Maximum": 4
        }
    ]
}

=== Outsmart-OOH/ooh_open_direct/examples/OOHpenDirect_1-5-1_v-1/POST_avails_(and)_request_001.json
{
    "$schema": "https://raw.githubusercontent.com/Outsmart-OOH/ooh_open_direct/master/schema/v1/uris/products/products_avails_request.json",
    "AccountId": "23873345",
    "EndDate": "2014-12-10T18:00:00.000Z",
    "ProductIds": [
        "456366"
    ],
    "StartDate": "2014-12-05T06:00:00.000Z",
    "AvailabilityFields": [
        {
            "Name": "Inventory",
            "Type": "Frames",
            "DataSource": "Space",
            "Target": "frame_id"
        },
        {
            "Name": "Delivery",
            "Type": "Frames",
            "DataSource": "ShareOfDisplay",
            "Target": "ShareOfTime"
        },
        {
            "Name": "Inventory",
            "Type": "Audience",
            "DataSource": "Metrics",
            "Target": "Impacts"
        },
        {
            "Name": "Investment",
            "Type": "Total",
            "DataSource": "GBP",
            "Target": "Fixed"
        }
    ],
    "Grouping": [
        {
            "Name": "Inventory",
            "Type": "Frames",
            "DataSource": "Space",
            "Target": "frame_id"
        }
    ],
    "Targeting": [
        {
            "$and": [
                {
                    "$and": [
                        {
                            "Name": "Inventory",
                            "Type": "Frames",
                            "DataSource": "Space",
                            "Target": "frame_id",
                            "TargetValues": [
                                "1234931339",
                                "1235190735"
                            ]
                        },
                        {
                            "Name": "Delivery",
                            "Type": "Frames",
                            "DataSource": "Time",
                            "Target": "Days",
                            "TargetValues": [
                                "5",
                                "6"
                            ]
                        },
                        {
                            "Name": "Delivery",
                            "Type": "Frames",
                            "DataSource": "ShareOfDisplay",
                            "Target": "ShareOfTime",
                            "TargetValues": [
                                "10"
                            ]
                        },
                        {
                            "Name": "Delivery",
                            "Type": "Frames",
                            "DataSource": "ShareOfDisplay",
                            "Target": "Spot",
                            "TargetValues": [
                                "5"
                            ]
                        }
                    ]
                },
                {
                    "$and": [
                        {
                            "Name": "Inventory",
                            "Type": "Frames",
                            "DataSource": "Space",
                            "Target": "frame_id",
                            "TargetValues": [
                                "1234931338",
                                "1235191547"
                            ]
                        },
                        {
                            "Name": "Delivery",
                            "Type": "Frames",
                            "DataSource": "Time",
                            "Target": "Days",
                            "TargetValues": [
                                "5",
                                "6"
                            ]
                        },
                        {
                            "Name": "Delivery",
                            "Type": "Frames",
                            "DataSource": "ShareOfDisplay",
                            "Target": "ShareOfTime",
                            "TargetValues": [
                                "20"
                            ]
                        },
                        {
                            "Name": "Delivery",
                            "Type": "Frames",
                            "DataSource": "ShareOfDisplay",
                            "Target": "Spot",
                            "TargetValues": [
                                "5"
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}

=== Outsmart-OOH/ooh_open_direct/examples/Worksheets/Outsmart_PostingCycle/RequestExample/POST_avails_(frames)_request.json
{
    "$schema": "https://raw.githubusercontent.com/Outsmart-OOH/ooh_open_direct/master/schema/v1/uris/products/products_avails_request.json",
    "AccountId": "23873345",
    "EndDate": "2021-02-07T00:00:00Z",
    "ProductIds": [
        "RoadsideClassic48s"
    ],
    "StartDate": "2021-11-01T00:00:00Z",
    "AvailabilityFields": [
        {
            "Name": "Inventory",
            "Type": "Frames",
            "DataSource": "Space",
            "Target": "frame_id"
        },
        {
            "Name": "Inventory",
            "Type": "Audience",
            "DataSource": "Metrics",
            "Target": "Impacts"
        },
        {
            "Name": "Investment",
            "Type": "Total",
            "DataSource": "GBP",
            "Target": "Fixed"
        }
    ],
    "Grouping": [
        {
            "Name": "Inventory",
            "Type": "Frames",
            "DataSource": "Space",
            "Target": "frame_id"
        }
    ],
    "Targeting": [
        {
            "Name": "Inventory",
            "Type": "Frames",
            "DataSource": "Space",
            "Target": "frame_id",
            "TargetValues": [
                "1234931339",
                "1235190735",
                "1234931338",
                "1235191547"
            ]
        },
        {
            "Name": "Delivery",
            "Type": "Frames",
            "DataSource": "Outsmart",
            "Target": "PostingCycle",
            "TargetValues": [
                "2021-2",
                "2021-3"
            ]
        }
    ]
}

=== Outsmart-OOH/ooh_open_direct/examples/Worksheets/OOHbjectExamples1.5.1_April2021/2_POST_avails_(frames)_request_count.json
{
    "$schema": "https://raw.githubusercontent.com/Outsmart-OOH/ooh_open_direct/master/schema/v1/uris/products/products_avails_request.json",
    "AccountId": "23873345",
    "EndDate": "2014-12-10T18:00:00.000Z",
    "ProductIds": [ "456500" ],
    "StartDate": "2014-12-05T06:00:00.000Z",

    "AvailabilityFields": [


        {
            "Name": "Inventory",
            "Type": "Frames",
            "DataSource": "Space",
            "Target": "frame_id"
        },
        {
            "Name": "Inventory",
            "Type": "Frames",
            "DataSource": "Time",
            "Target": "Days"
        },
        {
            "Name": "Inventory",
            "Type": "Frames",
            "DataSource": "Time",
            "Target": "Hours"
        },
        {
            "Name": "Delivery",
            "Type": "Frames",
            "DataSource": "ShareOfDisplay",
            "Target": "ShareOfTime"
        },
        {
            "Name": "Inventory",
            "Type": "Audience",
            "DataSource": "Metrics",
            "Target": "Impacts"
        },
        {
            "Name": "Investment",
            "Type": "Total",
            "DataSource": "GBP",
            "Target": "Fixed"
        },
        {
            "Name": "Inventory",
            "Type": "Availability",
            "DataSource": "<Media Owner>",
            "Target":"Unavailable"
        },
        {
            "Name": "Inventory",
            "Type": "Availability",
            "DataSource": "<Media Owner>",
            "Target":"Available"
        }


    ],


    "Grouping": [
        {
            "Name": "Inventory",
            "Type": "Frames",
            "DataSource": "Space",
            "Target": "frame_id"
        }
    ],

    "Targeting": [
        {
            "Name": "Inventory",
            "Type": "FrameCount",
            "DataSource": "Space",
            "Target": "frame_id",
            "TargetValues": [
                "4"
            ],
            "Minimum": 2,
            "Maximum": 6
        },
        {
            "Name": "Inventory",
            "Type": "Audience",
            "DataSource": "Metrics",
            "Target": "Impacts",
            "TargetValues": ["800000"]
        },
        {
            "Name": "Delivery",
            "Type": "Frames",
            "DataSource": "Time",
            "Target": "Days",
            "TargetValues": [ "5", "6" ]

        },
        {
            "Name": "Delivery",
            "Type": "Frames",
            "DataSource": "ShareOfDisplay",
            "Target": "ShareOfTime",
            "TargetValues": ["20"]

        },
        {
            "Name": "Delivery",
            "Type": "Frames",
            "DataSource": "ShareOfDisplay",
            "Target": "Spot",
            "TargetValues": ["5"]

        }

    ]
}

=== Outsmart-OOH/ooh_open_direct/examples/Worksheets/Avails_Examples_x_DoNotUse/v_POST_avails_example_request.json
{
    "$schema": "https://raw.githubusercontent.com/Outsmart-OOH/ooh_open_direct/master/schema/v1/uris/products/products_avails_request.json",
    "AccountId": "23873345",
    "EndDate": "2014-12-10T18:00:00.000Z",
    "ProductIds": [
        "456367"
    ],
    "StartDate": "2014-12-05T06:00:00.000Z",
    "AvailabilityFields": [
        {
            "Name": "Inventory",
            "Type": "Frames",
            "DataSource": "Space",
            "Target": "frame_id"
        },
        {
            "Name": "Delivery",
            "Type": "Frames",
            "DataSource": "Time",
            "Target": "Days"
        },
        {
            "Name": "Delivery",
            "Type": "Frames",
            "DataSource": "Time",
            "Target": "Hours"
        },
        {
            "Name": "Delivery",
            "Type": "Frames",
            "DataSource": "ShareOfDisplay",
            "Target": "ShareOfTime"
        },
        {
            "Name": "Inventory",
            "Type": "Audience",
            "DataSource": "Metrics",
            "Target": "Impacts"
        },
        {
            "Name": "Investment",
            "Type": "Total",
            "DataSource": "GBP",
            "Target": "Fixed"
        }
    ],
    "Grouping": [
        {
            "Name": "Inventory",
            "Type": "Frames",
            "DataSource": "Space",
            "Target": "frame_id"
        },
        {
            "Name": "Delivery",
            "Type": "Frames",
            "DataSource": "Time",
            "Target": "Days"
        },
        {
            "Name": "Delivery",
            "Type": "Frames",
            "DataSource": "Time",
            "Target": "Hours"
        }
    ],
    "Targeting": [
        {
            "Name": "Inventory",
            "Type": "Frames",
            "DataSource": "Space",
            "Target": "frame_id",
            "TargetValues": [
                "1234931339"
            ]
        },
        {
            "Name": "Delivery",
            "Type": "Frames",
            "DataSource": "Time",
            "Target": "Hours",
            "TargetValues": [
                "5",
                "6"
            ]
        },
        {
            "Name": "Delivery",
            "Type": "Frames",
            "DataSource": "Time",
            "Target": "Day",
            "TargetValues": [
                "1",
                "2"
            ]
        },
        {
            "Name": "Delivery",
            "Type": "Frames",
            "DataSource": "ShareOfDisplay",
            "Target": "ShareOfTime",
            "TargetValues": [
                "20"
            ]
        }
    ]
}

=== Outsmart-OOH/ooh_open_direct/examples/OOHpenDirect_1-5-1_v-1/POST_avails_(audience)_request.json
{
    "$schema": "https://raw.githubusercontent.com/Outsmart-OOH/ooh_open_direct/master/schema/v1/uris/products/products_avails_request.json",
    "AccountId": "23873345",
    "EndDate": "2014-12-10T18:00:00.000Z",
    "ProductIds": [ "456366" ],
    "StartDate": "2014-12-05T06:00:00.000Z",

    "AvailabilityFields": [


        {
            "Name": "Inventory",
            "Type": "Frames",
            "DataSource": "Space",
            "Target": "frame_id"
        },
        {
            "Name": "Delivery",
            "Type": "Frames",
            "DataSource": "ShareOfDisplay",
            "Target": "ShareOfTime"
        },
        {
            "Name": "Inventory",
            "Type": "Audience",
            "DataSource": "Metrics",
            "Target": "Impacts"
        },
        {
            "Name": "Investment",
            "Type": "Total",
            "DataSource": "GBP",
            "Target": "Fixed"
        }


    ],


    "Grouping": [
        {
            "Name": "Inventory",
            "Type": "Frames",
            "DataSource": "Space",
            "Target": "frame_id"
        }
    ],

    "Targeting": [
        {
            "Name": "Inventory",
            "Type": "Frames",
            "DataSource": "<SPACE>",
            "Target": "<frame_id>",
            "TargetValues": [
                "1234931339",
                "1235190735",
                "1234931338",
                "1235191547"
            ]
        },
        {
            "Name": "Inventory",
            "Type": "Audience",
            "DataSource": "<ROUTE>",
            "Target": "<age>",
            "TargetValues": [
                "15-17",
                "18-24",
                "25-29"
            ]
        },
        {
            "Name": "Inventory",
            "Type": "Audience",
            "DataSource": "<ROUTE>",
            "Target": "<sex>",
            "TargetValues": [
                "Female"
            ]
        },
        {
            "Name": "Inventory",
            "Type": "Audience",
            "DataSource": "<ROUTE>",
            "Target": "<affluence>",
            "TargetValues": [
                "A",
                "B",
                "C1"
            ]
        },
        {
            "Name": "Inventory",
            "Type": "Audience",
            "DataSource": "Metrics",
            "Target": "Impacts",
            "TargetValues": ["8000"]
        }

    ]
}

=== Outsmart-OOH/ooh_open_direct/examples/OOHpenDirect_1-5-1_v-1/POST_avails_(frames)_no_targeting.json
{
    "$schema": "https://raw.githubusercontent.com/Outsmart-OOH/ooh_open_direct/master/schema/v1/uris/products/products_avails_request.json",
    "AccountId": "23873345",
    "EndDate": "2014-12-10T18:00:00.000Z",
    "ProductIds": [ "456366" ],
    "StartDate": "2014-12-05T06:00:00.000Z",

    "AvailabilityFields": [


        {
            "Name": "Inventory",
            "Type": "Frames",
            "DataSource": "Space",
            "Target": "frame_id"
        },
        {
            "Name": "Delivery",
            "Type": "Frames",
            "DataSource": "ShareOfDisplay",
            "Target": "ShareOfTime"
        },
        {
            "Name": "Inventory",
            "Type": "Audience",
            "DataSource": "Metrics",
            "Target": "Impacts"
        },
        {
            "Name": "Investment",
            "Type": "Frames",
            "DataSource": "GBP",
            "Target": "Fixed"
        }


    ],


    "Grouping": [
        {
            "Name": "Inventory",
            "Type": "Frames",
            "DataSource": "Space",
            "Target": "frame_id"
        }
    ],

    "Targeting": [

    ]
}

=== Outsmart-OOH/ooh_open_direct/examples/Worksheets/OOHbjectExamples1.5.1_April2021/4_POST_avails_request_tolerance.json
{
    "$schema": "https://raw.githubusercontent.com/Outsmart-OOH/ooh_open_direct/master/schema/v1/uris/products/products_avails_request.json",
    "AccountId": "23873345",
    "StartDate": "2021-07-05T06:00:00.000Z",
    "EndDate": "2021-05-18T18:00:00.000Z",
    "ProductIds": [
        "456500"
    ],
    "AvailabilityFields": [
        {
            "Name": "Inventory",
            "Type": "Frames",
            "DataSource": "Space",
            "Target": "frame_id"
        },
        {
            "Name": "Inventory",
            "Type": "Frames",
            "DataSource": "Time",
            "Target": "Days"
        },
        {
            "Name": "Delivery",
            "Type": "Frames",
            "DataSource": "ShareOfDisplay",
            "Target": "ShareOfTime"
        },
        {
            "Name": "Inventory",
            "Type": "Audience",
            "DataSource": "Metrics",
            "Target": "Impacts"
        },
        {
            "Name": "Investment",
            "Type": "Total",
            "DataSource": "GBP",
            "Target": "Fixed"
        }
    ],
    "Grouping": [
        {
            "Name": "Inventory",
            "Type": "Frames",
            "DataSource": "Space",
            "Target": "frame_id"
        }
    ],
    "Targeting": [
        {
            "Name": "Inventory",
            "Type": "Frames",
            "DataSource": "Space",
            "Target": "frame_id",
            "Minimum": 5,
            "Maximum": 5
        },
        {
            "Name": "Inventory",
            "Type": "Audience",
            "DataSource": "Metrics",
            "Target": "Impacts",
            "Minimum": 5000000,
            "Maximum": 5500000
        },
        {
            "Name": "Investment",
            "Type": "Total",
            "DataSource": "GBP",
            "Target": "Fixed",
            "Minimum": 5000,
            "Maximum": 6000
        }
    ]
}
